const modelStatus = {
    INSTALLING: 'INSTALLING',
    INSTALLED: 'INSTALLED',
}

const connectionStatus = {
    REQUESTED: 'REQUESTED',
    GRANTED: 'GRANTED',
    BLOCKED: 'BLOCKED',
}

const MESSAGES = {
    CALL_PIPE_REQUEST: 'CALL_PIPE_REQUEST',
    GET_PIPES_REQUEST: 'GET_PIPES_REQUEST',
    GET_PIPES_RESPONSE: 'GET_PIPES_RESPONSE',
    DELETE_PIPE_REQUEST: 'DELETE_PIPE_REQUEST',
    DELETE_PIPE_RESPONSE: 'DELETE_PIPE_RESPONSE',
    LOAD_PIPE_REQUEST: 'LOAD_PIPE_REQUEST',
    LOAD_PIPE_RESPONSE: 'LOAD_PIPE_RESPONSE',
    STREAM: 'STREAM',
}


module.exports = {
    modelStatus,
    connectionStatus,
    ...MESSAGES
}